import { AiFillInstagram, AiFillSafetyCertificate } from "react-icons/ai";
import {
  FaAward,
  FaBoxOpen,
  FaDev,
  FaDribbble,
  FaFacebookF,
  FaGithub,
  FaGithubAlt,
  FaInfoCircle,
  FaInstagram,
  FaLink,
  FaLinkedinIn,
  FaMapSigns,
  FaSignLanguage,
  FaSkiing,
  FaTwitter,
} from "react-icons/fa";
import { GoTools } from "react-icons/go";
import { IoIosDocument, IoIosJournal } from "react-icons/io";
import {
  MdLocationOn,
  MdMenu,
  MdMoreHoriz,
  MdPerson,
  MdSchool,
  MdWork,
} from "react-icons/md";

export {
  AiFillInstagram,
  AiFillSafetyCertificate,
  FaAward,
  FaBoxOpen,
  FaDev,
  FaDribbble,
  FaFacebookF,
  FaGithub,
  FaGithubAlt,
  FaInfoCircle,
  FaInstagram,
  FaLink,
  FaLinkedinIn,
  FaMapSigns,
  FaSignLanguage,
  FaSkiing,
  FaTwitter,
  GoTools,
  IoIosDocument,
  IoIosJournal,
  MdLocationOn,
  MdMenu,
  MdMoreHoriz,
  MdPerson,
  MdSchool,
  MdWork,
};
