import { AiFillInstagram, AiFillSafetyCertificate } from "react-icons/ai";
import {
  FaAngleRight,
  FaAward,
  FaBoxOpen,
  FaDev,
  FaDribbble,
  FaFacebookF,
  FaGithub,
  FaGithubAlt,
  FaHeart,
  FaInfoCircle,
  FaInstagram,
  FaLink,
  FaLinkedinIn,
  FaPaintBrush,
  FaSignLanguage,
  FaStar,
  FaTwitter,
} from "react-icons/fa";
import { GoTools } from "react-icons/go";
import {
  IoIosDocument,
  IoIosJournal,
  IoIosMoon,
  IoIosPaperPlane,
  IoIosSunny,
} from "react-icons/io";
import {
  MdLocationOn,
  MdMenu,
  MdMoreHoriz,
  MdMusicNote,
  MdPerson,
  MdSchool,
  MdWork,
} from "react-icons/md";

export {
  AiFillInstagram,
  AiFillSafetyCertificate,
  FaAngleRight,
  FaAward,
  FaBoxOpen,
  FaDev,
  FaDribbble,
  FaFacebookF,
  FaGithub,
  FaGithubAlt,
  FaHeart,
  FaInfoCircle,
  FaInstagram,
  FaLink,
  FaLinkedinIn,
  FaPaintBrush,
  FaSignLanguage,
  FaStar,
  FaTwitter,
  GoTools,
  IoIosDocument,
  IoIosJournal,
  IoIosMoon,
  IoIosPaperPlane,
  IoIosSunny,
  MdLocationOn,
  MdMenu,
  MdMoreHoriz,
  MdMusicNote,
  MdPerson,
  MdSchool,
  MdWork,
};
